---
title: "Two Candidate Voting Bayesian"
author: "Jacky Lyu"
date: "22/08/2022"
output: html_document
---
```{r}
tc_Bayesian <- function(data, wR, max_size=1000, v=0.05){
  Y = sample(data, max_size, replace = TRUE)
  winner_count = cumsum(Y == wR)
  sample_size = 1:max_size
  
  Sn = Bayesian_Factor(sample_size, winner_count)
  
  h = (1-v)/v
  Test = which(Sn>h)
  if (length(test) == 0){
    return (list(max_size, FALSE))
  } else {
    return(list(Test[1], TRUE))
  }
}

my_dbinom <- function(size, success) {
  my_binom <- function(p) dbinom(success, size, p)
  return(my_binom)
}

Bayesian_Factor <- function(size, success){
  
  H0_likelihood = integrate(my_dbinom(size, success), 0, 0.5)$value
  H1_likelihood = integrate(my_dbinom(size, success), 0.5, 1)$value
  return (H1_likelihood/H0_likelihood)
  
}

test = function(a,b){
  return (my_dbinom(a,b)(0.2))
}

```

Simulation function for two candidate ballots, for a given pT, upset probability limit v.
```{r}
# perform one simulation on the Bayesian. Returns mean sample size, power, and significiance level.
tc_Bayesian_simulation <- function(pT, ntrials=1000, trial_size=10000, up_limit=0.05){
  
  correct_certifications = 0
  incorrect_certifications = 0
  
  data = tc_create_data(trial_size, pT, "Damjan", "Alex")
  
  #first, set the reported probability with the reported winner as true winner (correct report) 
  wT = tcfind_winner(data)
  
  correct_winner_trials = replicate(ntrials, tc_Bayesian(data, wT, v=up_limit))
  cw_sample_sizes = correct_winner_trials[1,]
  cw_outcomes = correct_winner_trials[2,]
  correct_certifications = sum(cw_outcomes == TRUE)
  
  power = correct_certifications/ntrials
  
  #then, test the reported probability with an actually false reported winner (false report)
  lT = tcfind_loser(data)
  
  false_winner_trials = replicate(ntrials, tc_Bayesian(data, lT, v=up_limit))
  fw_sample_sizes = false_winner_trials[1,]
  fw_outcomes = false_winner_trials[2,]
  incorrect_certifications = sum(fw_outcomes == TRUE)
  
  sig_level = incorrect_certifications/ntrials
  
  #lastly, calculate the mean sample size tested
  mean_sample_size = mean(unlist(list(cw_sample_sizes, fw_sample_sizes)))
  
  return (list(power, sig_level, mean_sample_size))
}

```
